language: php

php:
  - 7.0
  - 7.1

sudo: false

addons:
  apt:
    packages:
    - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - export COMPOSER_PROCESS_TIMEOUT=1800;
  - export TYPO3_PATH_ROOT=$TRAVIS_BUILD_DIR/.Build/Web;
  - export CODECLIMATE_REPO_TOKEN=99b1dd6f13ad2ce5baa590c4157d18c65876e747c60b03b8b214a34324043245;
  - cp .Build/Tests/composer.json .
  - mkdir -p .Build/Tests/Coverage
  - composer install

script:
  - >
    echo;
    echo "Running php lint";
    find . \( -path "./.Build" -o -path "./vendor" \) -prune -o -name \*.php -print | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    php .Build/bin/phpunit --colors --configuration .Build/Tests/UnitTests.xml --coverage-php=.Build/Tests/Coverage/UnitTests.cov;
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    php .Build/bin/phpunit --colors --configuration .Build/Tests/FunctionalTests.xml --coverage-php=.Build/Tests/Coverage/FunctionalTests.cov;

after_script:
  - mkdir -p build/logs/
  - php .Build/bin/phpcov merge .Build/Tests/Coverage --clover build/logs/clover.xml
  - php .Build/bin/test-reporter
